project:
  type: book

book:
  title: "Conceitos Iniciais de Álgebra Linear aplicados à Estatística"
  author: "Arthur Roque"
  date: "21/04/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - o_que_e_al.qmd
    - produto_interno.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

